import { Colors } from './utils';

export const debug = true;
export const emotes = {
    success: ':white_check_mark:',
    error: ':x:',
    bug: ':bug:',
    input: ':inbox_tray:',
    output: ':outbox_tray:',
    loading: ':hourglass_flowing_sand:',
    warning: ':warning:',
    info: ':information_source:',
    utils: ':mag_right:',
    fun: ':tada:',
    admin: ':gear:',
    owner: ':crown:',
    music: ':musical_note:',
    cat: ':cat:',
    fox: ':fox:',
    hug: ':hugging:',
    kiss: ':kissing_heart:',
    pat: ':handshake:',
    slap: ':raised_hand_with_fingers_splayed:',
    tickle: ':smirk_cat:',
    cuddle: ':smiling_face_with_3_hearts:',
    poke: ':point_right:',
    feed: ':fork_and_knife:',
    lewd: ':smirk:',
    id: ':id:',
    pen: ':pen_ballpoint:',
    reload: ':arrows_counterclockwise:',
    restart: ':arrows_counterclockwise:',
    infos: ':information_source:',
    help: ':question:',
    ping: ':ping_pong:',
    eval: ':desktop:',
    guilds: ':shield:',
    silhouettes: ':busts_in_silhouette:',
    uptime: ':stopwatch:',
    version: ':label:',
    status: ':satellite:',
    channels: ':speech_balloon:',
    commands: ':keyboard:',
    time: ':alarm_clock:',
    gear: ':gear:',
    api: ':satellite:',
    question: ':grey_question:',
    search: ':mag:',
    eightball: ':8ball:',
    hashtag: ':hash:',
    at: ':identification_card:',
    clock: ':clock1:',
}
export const colors: Colors = {
    success: '#4fd92a',
    error: '#f44336',
    bug: '#FF0000',
    warning: '#ff9800',
    info: '#2196f3',
    loading: '#FFFF00',
    debug: '#77c4fd',
    main: '#eb7763',
    secondary: '#adadad'
};
export const owners = [
    '662227196814819349'
];
export const devGuildId = '833638211342434324';